### ISSUE TITLE
problem with ajax links on IE9

### ISSUE THREAD

**Issue by alcroman** [ronalchn/ajax_pagination#2] opened 2012-11-09 20:02 UTC
Thanks for your great work. 
I'm working on application that uses ajax_pagination gem. It works fine on latest Chrome and Firefox. But I've met with a trouble on IE (ver. 9.0.8112.16421 32- and 64-bin; Win7): when I click on some ajax link, it shows neverendless spin and there is no response. I've try to run your demo and the problem comes again.

**Comment by ronalchn** [comment] 2012-11-09 20:07
Thank you for reporting this bug. I have never tested with IE, since I find it quite unsatisfying to use. It will take some time for me to setup IE to test and fix this problem.

**Comment by ronalchn** [comment] 2013-01-02 04:05
I have tested this on a production site on Windows 8, Internet Explorer 10. Since it works in the latest version of Internet Explorer, I don't think it is worthwhile for me to spend time fixing this. I haven't tried reproducing this problem in IE9. I won't fix this bug, if it does in fact occur.

While I won't fix this, I will accept any pull requests fixing such a problem. Unless somebody expresses an interest in fixing this, I will close this issue.

**Closed as completed by ronalchn** 2013-01-02 04:05 UTC
